easy_admin:
    site_name: 'Hospital'
    entities:
        Usuario:
            class: UserBundle\Entity\Usuario
            list:
                fields: ['nombre','apellidos','telefono','username','email','enabled','lastLogin','roles']
            new:
                fields: ['nombre','apellidos','telefono','username','email','enabled','password','roles']
            edit:
                fields: ['nombre','apellidos','telefono','username','email','enabled','lastLogin','password','expiresAt','locked','expired','roles']
        Paciente:
            class: AppBundle\Entity\Paciente
        IngresoPaciente:
            class: AppBundle\Entity\IngresoPaciente
