contact:
    resource: "@ContactBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /