AppBundle\Entity\Cie10:
    type: entity
    table: cie10
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        codigo:
            type: string
            nullable: false
            length: 5
            options:
                fixed: false
        enfermedad:
            type: string
            nullable: false
            length: 254
            options:
                fixed: false
    lifecycleCallbacks: {  }
